[project]
name = 'Blockchain-Based-Healthcare-Provider-Network-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.network-participation]
path = 'contracts/network-participation.clar'
clarity_version = 2
epoch = 2.5

[contracts.provider-verification]
path = 'contracts/provider-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.service-rate]
path = 'contracts/service-rate.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
